import webapp2
from google.appengine.ext import ndb
class buggs(ndb.Model):
    report_id=ndb.StringProperty(indexed=False)
    app_version_code=ndb.FloatProperty(indexed=False)
    app_version_name=ndb.StringProperty(indexed=False)
    package_name=ndb.StringProperty(indexed=False)
    file_path=ndb.StringProperty(indexed=False)
    phone_model=ndb.StringProperty(indexed=False)
    brand=ndb.StringProperty(indexed=False)
    product=ndb.StringProperty(indexed=False)
    android_version=ndb.StringProperty(indexed=False)
    build=ndb.StringProperty(indexed=False)
    total_mem_size=ndb.StringProperty(indexed=False)
    available_mem_size=ndb.StringProperty(indexed=False)
    custom_data=ndb.StringProperty(indexed=False)
    stack_trace=ndb.StringProperty(indexed=False)
    initial_conf=ndb.StringProperty(indexed=False)
    crash_conf=ndb.StringProperty(indexed=False)
    display=ndb.StringProperty(indexed=False)
    user_comment=ndb.StringProperty(indexed=False)
    user_app_start_date=ndb.StringProperty(indexed=False)
    user_crash_date=ndb.StringProperty(indexed=False)
    dumpsys_meminfo=ndb.StringProperty(indexed=False)
    dropbox=ndb.StringProperty(indexed=False)
    logcat=ndb.StringProperty(indexed=False)
    eventslog=ndb.StringProperty(indexed=False)
    radiolog=ndb.StringProperty(indexed=False)
    is_silent=ndb.StringProperty(indexed=False)
    device_id=ndb.StringProperty(indexed=False)
    installation_id=ndb.StringProperty(indexed=False)
    user_email=ndb.StringProperty(indexed=False)
    device_features=ndb.StringProperty(indexed=False)
    environment=ndb.StringProperty(indexed=False)
    shared_preferences=ndb.StringProperty(indexed=False)
    settings_system=ndb.StringProperty(indexed=False)
    settings_secure=ndb.StringProperty(indexed=False)

class buggs_insert(webapp2.RequestHandler):
    def post(self):
        buggs_obj = buggs()
        buggs_obj.report_id=self.request.get('report_id')
        buggs_obj.app_version_code=self.request.get('app_version_code')
        buggs_obj.app_version_name=self.request.get('app_version_name')
        buggs_obj.package_name=self.request.get('package_name')
        buggs_obj.file_path=self.request.get('file_path')
        buggs_obj.phone_model=self.request.get('phone_model')
        buggs_obj.brand=self.request.get('brand')
        buggs_obj.product=self.request.get('product')
        buggs_obj.android_version=self.request.get('android_version')
        buggs_obj.build=self.request.get('build')
        buggs_obj.total_mem_size=self.request.get('total_mem_size')
        buggs_obj.available_mem_size=self.request.get('available_mem_size')
        buggs_obj.custom_data=self.request.get('custom_data')
        buggs_obj.stack_trace=self.request.get('stack_trace')
        buggs_obj.initial_conf=self.request.get('initial_conf')
        buggs_obj.crash_conf=self.request.get('crash_conf')
        buggs_obj.display=self.request.get('display')
        buggs_obj.user_comment=self.request.get('user_comment')
        buggs_obj.user_app_start_date=parse_date(self.request.get('user_app_start_date'))
        buggs_obj.user_crash_date=pase_date(self.request.get('user_crash_date'))
        buggs_obj.dumpsys_meminfo=self.request.get('dumpsys_meminfo')
        buggs_obj.dropbox=self.request.get('dropbox')
        buggs_obj.logcat=self.request.get('logcat')
        buggs_obj.eventslog=self.request.get('eventslog')
        buggs_obj.radiolog=self.request.get('radiolog')
        buggs_obj.is_silent=self.request.get('is_silent')
        buggs_obj.device_id=self.request.get('device_id')
        buggs_obj.installation_id=self.request.get('installation_id')
        buggs_obj.user_email=self.request.get('user_email')
        buggs_obj.device_features=self.request.get('device_features')
        buggs_obj.environment=self.request.get('environment')
        buggs_obj.shared_preferences=self.request.get('shared_preferences')
        buggs_obj.settings_system=self.request.get('settings_system')
        buggs_obj.settings_secure=self.request.get('settings_secure')
        buggs_obj.put()

        def parse_date(date_str):
            #ToDo
#date_str=string "Y-m-d,H:i:s" from date_str;
            return date_str

application = webapp2.WSGIApplication([('/',buggs_insert)], debug=True)
