import webapp2
from google.appengine.ext import ndb
class buggs(ndb.Model):
    report_id=ndb.StringProperty(indexed=False)
    app_version_code=ndb.IntegerProperty(indexed=False)
    app_version_name=ndb.StringProperty(indexed=False)
    package_name=ndb.StringProperty(indexed=False)
    file_path=ndb.StringProperty(indexed=False)
    phone_model=ndb.StringProperty(indexed=False)
    brand=ndb.StringProperty(indexed=False)
    product=ndb.StringProperty(indexed=False)
    android_version=ndb.StringProperty(indexed=False)
    build=ndb.StringProperty(indexed=False)
    total_mem_size=ndb.StringProperty(indexed=False)
    available_mem_size=ndb.StringProperty(indexed=False)
    custom_data=ndb.StringProperty(indexed=False)
    stack_trace=ndb.StringProperty(indexed=False)
    initial_conf=ndb.StringProperty(indexed=False)
    crash_conf=ndb.StringProperty(indexed=False)
    display=ndb.StringProperty(indexed=False)
    user_comment=ndb.StringProperty(indexed=False)
    user_app_start_date=ndb.StringProperty(indexed=False)
    user_crash_date=ndb.StringProperty(indexed=False)
    dumpsys_meminfo=ndb.StringProperty(indexed=False)
    dropbox=ndb.StringProperty(indexed=False)
    logcat=ndb.StringProperty(indexed=False)
    eventslog=ndb.StringProperty(indexed=False)
    radiolog=ndb.StringProperty(indexed=False)
    is_silent=ndb.StringProperty(indexed=False)
    device_id=ndb.StringProperty(indexed=False)
    installation_id=ndb.StringProperty(indexed=False)
    user_email=ndb.StringProperty(indexed=False)
    device_features=ndb.StringProperty(indexed=False)
    environment=ndb.StringProperty(indexed=False)
    shared_preferences=ndb.StringProperty(indexed=False)
    settings_system=ndb.StringProperty(indexed=False)
    settings_secure=ndb.StringProperty(indexed=False)

class buggs_insert(webapp2.RequestHandler):
    def post(self):
        buggs_obj = buggs()
        buggs_obj.report_id=self.request.get('REPORT_ID')
        buggs_obj.app_version_code=int(self.request.get('APP_VERSION_CODE'))
        buggs_obj.app_version_name=self.request.get('APP_VERSION_NAME')
        buggs_obj.package_name=self.request.get('PACKAGE_NAME')
        buggs_obj.file_path=self.request.get('FILE_PATH')
        buggs_obj.phone_model=self.request.get('PHONE_MODEL')
        buggs_obj.brand=self.request.get('BRAND')
        buggs_obj.product=self.request.get('PRODUCT')
        buggs_obj.android_version=self.request.get('ANDROID_VERSION')
        buggs_obj.build=self.request.get('BUILD')
        buggs_obj.total_mem_size=self.request.get('TOTAL_MEM_SIZE')
        buggs_obj.available_mem_size=self.request.get('AVAILABLE_MEM_SIZE')
        buggs_obj.custom_data=self.request.get('CUSTOM_DATA')
        buggs_obj.stack_trace=self.request.get('STACK_TRACE')
        buggs_obj.initial_conf=self.request.get('INITIAL_CONFIGURATION')
        buggs_obj.crash_conf=self.request.get('CRASH_CONFIGURATION')
        buggs_obj.display=self.request.get('DISPLAY')
        buggs_obj.user_comment=self.request.get('USER_COMMENT')
        buggs_obj.user_app_start_date=self.request.get('USER_APP_START_DATE')
        buggs_obj.user_crash_date=self.request.get('USER_CRASH_DATE')
        buggs_obj.dumpsys_meminfo=self.request.get('DUMPSYS_MEMINFO')
        buggs_obj.dropbox=self.request.get('DROPBOX')
        buggs_obj.logcat=self.request.get('LOGCAT')
        buggs_obj.eventslog=self.request.get('EVENTSLOG')
        buggs_obj.radiolog=self.request.get('RADIOLOG')
        buggs_obj.is_silent=self.request.get('IS_SILENT')
        buggs_obj.installation_id=self.request.get('INSTALLATION_ID')
        buggs_obj.user_email=self.request.get('USER_EMAIL')
        buggs_obj.device_features=self.request.get('DEVICE_FEATURES')
        buggs_obj.environment=self.request.get('ENVIRONMENT')
        buggs_obj.shared_preferences=self.request.get('SHARED_PREFERENCES')
        buggs_obj.settings_system=self.request.get('SETTINGS_SYSTEM')
        buggs_obj.settings_secure=self.request.get('SETTINGS_SECURE')
        buggs_obj.put() 

application = webapp2.WSGIApplication([('/',buggs_insert)], debug=True)
